spring.application.name=homeney
spring.datasource.username=postgres
spring.datasource.password=123
spring.datasource.url=jdbc:postgresql://localhost:5432/homeney
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
